# "$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = """
$username\
$hostname\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$golang\
$python\
$openstack\
$env_var\
$custom\
$sudo\
$cmd_duration\
$line_break\
$container\
$character"""

[directory]
truncate_to_repo = false
style = "bold green"
truncation_symbol = ".../"

[hostname]
ssh_only = false
style = "bold red"

[username]
show_always = true
format = "[$user]($style) on "

[golang]
format = 'via [$symbol]($style)'

[python]
#format = 'via [$symbol](\($virtualenv\)($style)'
format = 'via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
