# "$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 1000
add_newline = false
format = """
$username\
$hostname\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$golang\
$python\
$openstack\
$env_var\
$custom\
$sudo\
$cmd_duration\
$line_break\
$container\
$character"""

[username]
show_always = true
style_user = "bold 199"
format = "[$user]($style) in "

[hostname]
ssh_only = true
style = "bold red"

[directory]
truncate_to_repo = false
style = "bold yellow"
truncation_symbol = "…/"

[git_branch]
style = "bold 135"

[golang]
format = 'via [$symbol]($style)'

[python]
#format = 'via [$symbol](\($virtualenv\)($style)'
format = 'via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
